const shoes = [
    {
        id: 0,
        image: 'shoes/kito1.jpeg',
        title: 'kito',
        price: 3000,
        quantity: 1,
    },
    {
        id: 1,
        image: 'shoes/kito2.jpg',
        title: 'kito',
        price: 2500,
        quantity: 1,
    },
    {
        id: 2,
        image: 'shoes/56449c06f863ff21fee6a52.mobile-gallery-large.jpg',
        title: 'kito',
        price: 2000,
        quantity: 1,
    },
    {
        id: 3,
        image: 'shoes/basket1.jpg',
        title: 'basket',
        price: 10000,
        quantity: 1,
    },
    {
        id: 4,
        image: 'shoes/basket2.webp',
        title: 'basket',
        price: 15000,
        quantity: 1,
    },
    {
        id: 5,
        image: 'shoes/basket3.webp',
        title: 'basket',
        price: 20000,
        quantity: 1,
    },
    {
        id: 6,
        image: 'shoes/claquette1.jpg',
        title: 'claquette',
        price: 25000,
        quantity: 1,
    },
    {
        id: 7,
        image: 'shoes/claquette2.jpg',
        title: 'claquette',
        price: 30000,
        quantity: 1,
    },
    {
        id: 8,
        image: 'shoes/claquette3.webp',
        title: 'claquette',
        price: 1000,
        quantity: 1,
    },
    {
        id: 9,
        image: 'shoes/soulier1.jpg',
        title: 'soulier',
        price: 40000,
        quantity: 1,
    },
    {
        id: 10,
        image: 'shoes/soulier2.jpg',
        title: 'soulier',
        price: 60000,
        quantity: 1,
    },
    {
        id: 11,
        image: 'shoes/soulier3.webp',
        title: 'soulier',
        price: 50000,
        quantity: 1,
    },
];